# Site configuration for Jekyll (if using Jekyll for static site generation)
title: "Elegant Threads"
description: "Beautiful Indian fashion - Sarees, Kurtis, and Blouses"
url: "https://fashionfashionfashionreptile.netlify.app/"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md

# Include files
include:
  - _pages
  - admin

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
      category: "fashion"
      available: true
      featured: false
