backend:
  name: git-gateway
  branch: main

# Enable editorial workflow for content review
publish_mode: editorial_workflow

# Site URL for local development and production
site_url: https://fashionfashionfashionreptile.netlify.app
display_url: https://fashionfashionfashionreptile.netlify.app

# Logo for the admin interface
logo_url: https://fashionfashionfashionreptile.netlify.app/admin/logo.png

media_folder: static/uploads
public_folder: /static/uploads

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Product name (e.g., Silk Banarasi Saree)" }
      - { label: "Category", name: "category", widget: "select", options: ["sarees", "kurtis", "blouses"], hint: "Select the product category" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", min: 0, hint: "Price in INR (e.g., 2500)" }
      - { label: "Featured Image", name: "image", widget: "image", hint: "Main product image (recommended: 800x800px)" }
      - { label: "Description", name: "description", widget: "text", hint: "Brief product description for listings" }
      - { label: "Featured Product", name: "featured", widget: "boolean", default: false, hint: "Show on homepage featured section" }
      - { label: "Available for Sale", name: "available", widget: "boolean", default: true, hint: "Is this product currently available?" }
      - { label: "Tags", name: "tags", widget: "list", required: false, hint: "Keywords for search (e.g., silk, wedding, casual)" }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "", hint: "When to publish this product" }
      - { label: "Detailed Description", name: "body", widget: "markdown", required: false, hint: "Full product details, care instructions, etc." }

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Settings"
        name: "site"
        file: "content/settings/site.md"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Contact Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Social Links", name: "social", widget: "object", fields: [
              { label: "Instagram", name: "instagram", widget: "string", required: false },
              { label: "Facebook", name: "facebook", widget: "string", required: false },
              { label: "Pinterest", name: "pinterest", widget: "string", required: false }
            ]}
